#==============================================================
# List of things to build

PROG_LIST = mf

#include makefile to get rules
include $(AFIDS_ROOT)/AfidsMakefile.in

#==============================================================
# Add include/carto to include line. This avoids needing to
# change existing code by adding "carto/" to the include
# line.

CPPFLAGS += -I$(AFIDSTOP)/include/carto

CFLAGS += -Wmissing-prototypes -Wstrict-prototypes




