require "rubygems"
require "afids"
include Afids

# This reads the file generated by the POS Export utility from Applanix
#
# Note that we need to have the epoch that the Applanix time is relative to. 
# The Applanix can be configured in different modes, but normally the times
# reported are the "GPS seconds of the week", which is just the seconds from
# Sunday 0:00:00 UTC (i.e., just between Saturday and Sunday). As an aid, 
# there is the routine PosExportOrbit.start_of_week that converts a time
# somewhere in the week to the starting time. So, for example, you can get
# the time for one of the acquired images and use it to determine the start
# of the week.
#
# Note that the GPS time does not include leapseconds, while UTC time does. 
# The difference between these two times is 15 seconds as of 2009. In practice 
# this doesn't matter much, because we are really just using time here as
# an index number to look up the Applanix data. But we'll go ahead and
# include this to avoid confusion at some point in the future when this 
# might matter. We hardwire the number of leapseconds.

class PosExportOrbit
  def PosExportOrbit.start_of_week(tm)
    t = tm.utc
    y = t.year
    m = t.month
    d = t.day - t.strftime("%w").to_i
    Time.utc(y,m,d) + 15
  end
end
