# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded TMA 1.0 [list source [file join $dir tma.tcl]]
package ifneeded TMASRV 1.0 [list load tmaSrv.so]\n[list source [file join $dir minpath.tcl]]\n[list source [file join $dir weather.tcl]]\n[list source [file join $dir util.tcl]]\n[list source [file join $dir queryTerrain.tcl]]\n[list source [file join $dir vpf2vec.tcl]]\n[list source [file join $dir obstacles.tcl]]\n[list source [file join $dir contours.tcl]]\n[list source [file join $dir analyst.tcl]]\n[list source [file join $dir polygon.tcl]]\n[list source [file join $dir reportCorrelation.tcl]]\n[list source [file join $dir MUSESRV.tcl]]\n[list source [file join $dir tmasrv.tcl]]\n[list source [file join $dir rainbow.tcl]]\n[list source [file join $dir colorwheel.tcl]]\n[list source [file join $dir editMover.tcl]]\n[list source [file join $dir mover.tcl]]\n[list source [file join $dir analysisHistory.tcl]]
package ifneeded helpers 1.0 [list source [file join $dir genMover.tcl]]
