# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.89 94/08/12 00:45:51 gildea Exp $

#***********************************************************************
#
# This makefile is automatically generated by imake.  If you need to change
# the makefile, edit the .imake file and re-run imake, or contact the VICAR
# system programmer to change the imake templates.
#
# *** DO NOT EDIT THIS FILE!! ***
#
#***********************************************************************

#ident	"@(#)feature_tests.h	1.18	99/07/26 SMI"

#ident	"@(#)isa_defs.h	1.20	99/05/04 SMI"

#

UNIT_NAME = lplist
# VICAR program lplist

#
#***********************************************************************

CC = cc -Xa -DSOLARIS

SHELL = /bin/sh
CP = cp
CHMOD_X = chmod +x

AR = ar r

ARX = ar x

RM = rm -f
LN = ln -fs

RANLIB = /bin/true

RUN_TM  = taetm
MSGBLD  = $$TAEPDF/msgbld

LINK.c = $(CC)  $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c  $<

LDFLAGS =

CFLAGS = -O

CPPFLAGS =  -I$(V2INC) -I$(TAEINC)    -I$(P1INC)       -I$(P2INC)

OBJS = dbfopen.o shpopen.o fileutils.o MemUtils.o LPUtils.o lplist.o

INCLUDES =

CLEANOBJS = dbfopen.o shpopen.o fileutils.o MemUtils.o LPUtils.o lplist.o

CLEANSRC = dbfopen.c shpopen.c fileutils.c MemUtils.c LPUtils.c lplist.c

CLEANOTHER =

CLEANINC =

# Note that SYSTEMINC is used only for includes that are installed,
# e.g. from a TAO/IDL build.

LIBS = -L$(V2OLB)              -lp2sub   -lp1sub                             -lrtl             -lm   -lsocket -lnsl

std: lplist

all: lplist doc

system: lplist doc clean.obj clean.src

compile:  $(OBJS)

lplist:  $(OBJS)
	$(LINK.c) -o lplist $(OBJS) $(LIBS)

doc:

clean.obj:
	-$(RM) $(CLEANOBJS)

clean.src:
	-$(RM) $(CLEANSRC) $(CLEANINC) $(CLEANOTHER)
	-$(RM) $(UNIT_NAME).make $(UNIT_NAME).bld $(UNIT_NAME).imake

$(OBJS): $(INCLUDES)

